{"Id":81,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-14T15:07:18.4471358+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.101","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-14T12:07:18.4927497Z"},
{"Id":82,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-14T15:09:34.8087971+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.101","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-14T12:09:34.8093426Z"},
{"Id":83,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-14T16:00:06.4134354+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.101","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-14T13:00:06.453206Z"},
{"Id":84,"Message":"The view 'Index' was not found. Searched locations: /Views/EventLog/Index.cshtml, /Views/Shared/Index.cshtml","EventId":3,"LogLevel":"Error","IpAdress":"192.168.1.101","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-14T13:00:19.7564055Z"},
{"Id":85,"Message":"An unhandled exception has occurred while executing the request\nSystem.InvalidOperationException: The view 'Index' was not found. The following locations were searched:\r\n/Views/EventLog/Index.cshtml\r\n/Views/Shared/Index.cshtml\r\n   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)\r\n   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.101","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-14T13:00:19.813752Z"},
{"Id":86,"Message":"The view 'Index' was not found. Searched locations: /Views/EventLog/Index.cshtml, /Views/Shared/Index.cshtml","EventId":3,"LogLevel":"Error","IpAdress":"192.168.1.101","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-14T13:00:31.0106403Z"},
{"Id":87,"Message":"An unhandled exception has occurred while executing the request\nSystem.InvalidOperationException: The view 'Index' was not found. The following locations were searched:\r\n/Views/EventLog/Index.cshtml\r\n/Views/Shared/Index.cshtml\r\n   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)\r\n   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.101","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-14T13:00:31.0443375Z"},
{"Id":88,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-14T16:02:51.6451615+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.101","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-14T13:02:51.6885958Z"},
{"Id":89,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-14T16:03:30.634336+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.101","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-14T13:03:30.6349709Z"},
{"Id":90,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-14T16:04:24.7990876+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.101","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-14T13:04:24.7994139Z"},
{"Id":91,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-14T16:12:12.6485539+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.101","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-14T13:12:12.6920357Z"},
{"Id":92,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-14T16:13:23.3503811+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.101","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-14T13:13:23.3507841Z"},
{"Id":93,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-14T16:14:26.489835+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.101","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-14T13:14:26.4902723Z"},
{"Id":94,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-14T16:14:34.748554+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.101","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-14T13:14:34.7489665Z"},
{"Id":95,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-14T16:15:18.4354194+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.101","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-14T13:15:18.4357916Z"},
{"Id":96,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-14T16:34:14.3599309+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.101","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-14T13:34:14.3604446Z"},
{"Id":97,"Message":"An unhandled exception has occurred while executing the request\nSystem.InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'SampleCoreArch.Core.Common.Result`1[System.Collections.Generic.IEnumerable`1[SampleCoreArch.Core.Logging.EventLog]]', but this ViewDataDictionary instance requires a model item of type 'System.Collections.Generic.IEnumerable`1[SampleCoreArch.Core.Logging.EventLog]'.\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary.EnsureCompatible(Object value)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary..ctor(ViewDataDictionary source, Object model, Type declaredModelType)\r\n   at lambda_method(Closure , ViewDataDictionary )\r\n   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorPagePropertyActivator.CreateViewDataDictionary(ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorPagePropertyActivator.Activate(Object page, ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorPageActivator.Activate(IRazorPage page, ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__16.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__15.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.101","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-14T13:39:46.0659047Z"},
